kind: Deployment
apiVersion: apps/v1
metadata:
   name: devops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: devops
   template:
      metadata:
        labels:
          app: devops
      spec:
       containers:
        - name: devops
          image: pawar199813/dhiraj_job_2:v1.62
          imagePullPolicy: Always
          ports:
          - containerPort: 80 22
